using DoktorKlinik.Domain.Country;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DoktorKlinik.DataAccess.SeetData
{
    internal class CityData
    {
        public readonly static City Data01_Adana = new City() { Id = 1, Name = "Adana", CountryId =1 };
        public readonly static City Data02_Adıyaman = new City() { Id = 2, Name = "Adıyaman", CountryId = 1 };
        public readonly static City Data03_Afyon = new City() { Id = 3, Name = "Afyon", CountryId = 1 };
        public readonly static City Data04_Ağrı = new City() { Id = 4, Name = "Ağrı" , CountryId = 1 };
        public readonly static City Data05_Aksaray = new City() { Id = 5, Name = "Aksaray", CountryId = 1 };
        public readonly static City Data06_Amasya = new City() { Id = 6, Name = "Amasya" , CountryId = 1 };
        public readonly static City Data07_Ankara = new City() { Id = 7, Name = "Ankara" , CountryId = 1 };
        public readonly static City Data08_Antalya = new City() { Id = 8, Name = "Antalya" , CountryId = 1 };
        public readonly static City Data09_Ardahan = new City() { Id = 9, Name = "Ardahan" , CountryId = 1 };
        public readonly static City Data10_Artvin = new City() { Id = 10, Name = "Artvin" , CountryId = 1 };
        public readonly static City Data11_Aydın = new City() { Id = 11, Name = "Aydın" , CountryId = 1 };
        public readonly static City Data12_Balıkesir = new City() { Id = 12, Name = "Balıkesir" , CountryId = 1 };
        public readonly static City Data13_Bartın = new City() { Id = 13, Name = "Bartın" , CountryId = 1 };
        public readonly static City Data14_Batman = new City() { Id = 14, Name = "Batman" , CountryId = 1 };
        public readonly static City Data15_Bayburt = new City() { Id = 15, Name = "Bayburt" , CountryId = 1 };
        public readonly static City Data16_Bilecik = new City() { Id = 16, Name = "Bilecik", CountryId = 1 };
        public readonly static City Data17_Bingöl = new City() { Id = 17, Name = "Bingöl", CountryId = 1 };
        public readonly static City Data18_Bitlis = new City() { Id = 18, Name = "Bitlis", CountryId = 1 };
        public readonly static City Data19_Bolu = new City() { Id = 19, Name = "Bolu", CountryId = 1 };
        public readonly static City Data20_Burdur = new City() { Id = 20, Name = "Burdur", CountryId = 1 };
        public readonly static City Data21_Bursa = new City() { Id = 21, Name = "Bursa", CountryId = 1 };
        public readonly static City Data22_Çanakkale = new City() { Id = 22, Name = "Çanakkale", CountryId = 1 };
        public readonly static City Data23_Çankırı = new City() { Id = 23, Name = "Çankırı", CountryId = 1 };
        public readonly static City Data24_Çorum = new City() { Id = 24, Name = "Çorum", CountryId = 1 };
        public readonly static City Data25_Denizli = new City() { Id = 25, Name = "Denizli", CountryId = 1 };
        public readonly static City Data26_Diyarbakır = new City() { Id = 26, Name = "Diyarbakır", CountryId = 1 };
        public readonly static City Data27_Düzce = new City() { Id = 27, Name = "Düzce", CountryId = 1 };
        public readonly static City Data28_Edirne = new City() { Id = 28, Name = "Edirne", CountryId = 1 };
        public readonly static City Data29_Elazığ = new City() { Id = 29, Name = "Elazığ", CountryId = 1 };
        public readonly static City Data30_Erzincan = new City() { Id = 30, Name = "Erzincan", CountryId = 1 };
        public readonly static City Data31_Erzurum = new City() { Id = 31, Name = "Erzurum", CountryId = 1 };
        public readonly static City Data32_Eskişehir = new City() { Id = 32, Name = "Eskişehir", CountryId = 1 };
        public readonly static City Data33_Gaziantep = new City() { Id = 33, Name = "Gaziantep", CountryId = 1 };
        public readonly static City Data34_Giresun = new City() { Id = 34, Name = "Giresun", CountryId = 1 };
        public readonly static City Data35_Gümüşhane = new City() { Id = 35, Name = "Gümüşhane", CountryId = 1 };
        public readonly static City Data36_Hakkari = new City() { Id = 36, Name = "Hakkari", CountryId = 1 };
        public readonly static City Data37_Hatay = new City() { Id = 37, Name = "Hatay", CountryId = 1 };
        public readonly static City Data38_Iğdır = new City() { Id = 38, Name = "Iğdır", CountryId = 1 };
        public readonly static City Data39_Isparta = new City() { Id = 39, Name = "Isparta", CountryId = 1 };
        public readonly static City Data40_İstanbul = new City() { Id = 40, Name = "İstanbul", CountryId = 1 };
        public readonly static City Data41_İzmir = new City() { Id = 41, Name = "İzmir", CountryId = 1 };
        public readonly static City Data42_Kahramanmaraş = new City() { Id = 42, Name = "Kahramanmaraş", CountryId = 1 };
        public readonly static City Data43_Karabük = new City() { Id = 43, Name = "Karabük", CountryId = 1 };
        public readonly static City Data44_Karaman = new City() { Id = 44, Name = "Karaman", CountryId = 1 };
        public readonly static City Data45_Kars = new City() { Id = 45, Name = "Kars", CountryId = 1 };
        public readonly static City Data46_Kastamonu = new City() { Id = 46, Name = "Kastamonu", CountryId = 1 };
        public readonly static City Data47_Kayseri = new City() { Id = 47, Name = "Kayseri", CountryId = 1 };
        public readonly static City Data48_Kırıkkale = new City() { Id = 48, Name = "Kırıkkale", CountryId = 1 };
        public readonly static City Data49_Kırklareli = new City() { Id = 49, Name = "Kırklareli", CountryId = 1 };
        public readonly static City Data50_Kırşehir = new City() { Id = 50, Name = "Kırşehir", CountryId = 1 };
        public readonly static City Data51_Kilis = new City() { Id = 51, Name = "Kilis", CountryId = 1 };
        public readonly static City Data52_Kocaeli = new City() { Id = 52, Name = "Kocaeli", CountryId = 1 };
        public readonly static City Data53_Konya = new City() { Id = 53, Name = "Konya", CountryId = 1 };
        public readonly static City Data54_Kütahya = new City() { Id = 54, Name = "Kütahya", CountryId = 1 };
        public readonly static City Data55_Malatya = new City() { Id = 55, Name = "Malatya", CountryId = 1 };
        public readonly static City Data56_Manisa = new City() { Id = 56, Name = "Manisa", CountryId = 1 };
        public readonly static City Data57_Mardin = new City() { Id = 57, Name = "Mardin", CountryId = 1 };
        public readonly static City Data58_Mersin = new City() { Id = 58, Name = "Mersin", CountryId = 1 };
        public readonly static City Data59_Muğla = new City() { Id = 59, Name = "Muğla", CountryId = 1 };
        public readonly static City Data60_Muş = new City() { Id = 60, Name = "Muş", CountryId = 1 };
        public readonly static City Data61_Nevşehir = new City() { Id = 61, Name = "Nevşehir", CountryId = 1 };
        public readonly static City Data62_Niğde = new City() { Id = 62, Name = "Niğde", CountryId = 1 };
        public readonly static City Data63_Ordu = new City() { Id = 63, Name = "Ordu", CountryId = 1 };
        public readonly static City Data64_Osmaniye = new City() { Id = 64, Name = "Osmaniye", CountryId = 1 };
        public readonly static City Data65_Rize = new City() { Id = 65, Name = "Rize", CountryId = 1 };
        public readonly static City Data66_Sakarya = new City() { Id = 66, Name = "Sakarya", CountryId = 1 };
        public readonly static City Data67_Samsun = new City() { Id = 67, Name = "Samsun", CountryId = 1 };
        public readonly static City Data68_Siirt = new City() { Id = 68, Name = "Siirt", CountryId = 1 };
        public readonly static City Data69_Sinop = new City() { Id = 69, Name = "Sinop", CountryId = 1 };
        public readonly static City Data70_Sivas = new City() { Id = 70, Name = "Sivas", CountryId = 1 };
        public readonly static City Data71_Şanlıurfa = new City() { Id = 71, Name = "Şanlıurfa", CountryId = 1 };
        public readonly static City Data72_Şırnak = new City() { Id = 72, Name = "Şırnak", CountryId = 1 };
        public readonly static City Data73_Tekirdağ = new City() { Id = 73, Name = "Tekirdağ", CountryId = 1 };
        public readonly static City Data74_Tokat = new City() { Id = 74, Name = "Tokat", CountryId = 1 };
        public readonly static City Data75_Trabzon = new City() { Id = 75, Name = "Trabzon", CountryId = 1 };
        public readonly static City Data76_Tunceli = new City() { Id = 76, Name = "Tunceli", CountryId = 1 };
        public readonly static City Data77_Uşak = new City() { Id = 77, Name = "Uşak", CountryId = 1 };
        public readonly static City Data78_Van = new City() { Id = 78, Name = "Van", CountryId = 1 };
        public readonly static City Data79_Yalova = new City() { Id = 79, Name = "Yalova", CountryId = 1 };
        public readonly static City Data80_Yozgat = new City() { Id = 80, Name = "Yozgat", CountryId = 1 };
        public readonly static City Data81_Zonguldak = new City() { Id = 81, Name = "Zonguldak", CountryId = 1 };
    }
}
